
clear all
close all
home

fname='results/windmill_mhg_s_3_n_29_th_0.09.png';
h=figure;
I=imread(fname);
imshow(I,[]);
magnifyOnFigure(h, 'displayLinkStyle', 'straight',...
                    'EdgeColor', 'red',...
                    'magnifierShape', 'rectangle',...
                    'frozenZoomAspectratio', 'on',...
                    'secondaryAxesFaceColor', [1 0 0],...
                    'edgeWidth', 2);